import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

// Generated by drift_dev when running `dart run build_runner build`
part 'database.g.dart';

class TodoItems extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 1, max: 50)();
  TextColumn get description => text().nullable()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  BoolColumn get isCompleted => boolean().withDefault(const Constant(false))();
}

@DriftDatabase(tables: [TodoItems])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  Future<List<TodoItem>> getAllTodoItems() => select(todoItems).get();

  Stream<List<TodoItem>> watchAllTodoItems() => select(todoItems).watch();

  Future<int> insertTodoItem(TodoItemsCompanion todoItem) =>
      into(todoItems).insert(todoItem);

  Future<bool> updateTodoItem(TodoItem todoItem) =>
      update(todoItems).replace(todoItem);

  Future<int> deleteTodoItem(TodoItem todoItem) =>
      delete(todoItems).delete(todoItem);

  Future<List<TodoItem>> getCompletedTodosCustomSql() {
    return customSelect(
      'SELECT * FROM todo_items WHERE is_completed = 1 ORDER BY title DESC',
      readsFrom: {todoItems},
    ).map((row) {
      return todoItems.map(row.data);
    }).get();
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}
